name: Create Pull Request - Feature

on:
  push:
    branches:
      - feature/*
      
jobs:
  create-pull-request:
    name: Pull request feature
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_AUTO_PR }}
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_TITLE: ${{ steps.extract_branch.outputs.branch }}
          # PULL_REQUEST_DRAFT: true
          PULL_REQUEST_REVIEWERS: ${{ secrets.REVIEWERS }}
          PULL_REQUEST_BODY: |
              ## What does this PR do?
              ...

              ## Jira ticket number?

              ...

              ## Checklist before merging
              ---
              - [ ] My code follows this project's style guidelines.
              - [ ] If it is a core feature, I have added thorough tests.
              - [ ] I made the corresponding changes in the documentation.
              - [ ] Does it fit into the existing architecture?
              - [ ] Does it follow the standards adopted by the team in the project?
              - [ ] Is the code in the right place?
              - [ ] Is there code reuse?
              - [ ] Is the complexity too high?
              - [ ] Do the names that were used in variables, fields, parameters, classes and methods reflect what it really represents?
              - [ ] Only by reading the code is it possible to understand what it does?
              - [ ] Does the code contain a Bug, a wrong comparison?
