name: Develop CI

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
#test
env:
  CODE: "MAIN"

jobs:
  build:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo make build here! ${{ github.ref_name }}
          echo "${{ github.head_ref }}"

  deploy:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    environment: 
      name: develop
      url: 'https://develop-my-app.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo deploy develop

      - name: Set ENV Credentials
        run: |
          client_code=AWS_CREDENTIALS_${{env.CODE}}
          echo "::set-output name=secret::${client_code}"
        id: data

      - name: Serverless deploy
        run: |
          echo name: ${{steps.data.outputs.secret}}
          secret="${{ secrets[steps.data.outputs.secret] }}"
          AWS_ACCESS_KEY_ID=$(echo "$secret" | sed -n '1p')
          AWS_SECRET_ACCESS_KEY=$(echo "$secret" | sed -n '2p')
          echo "key aws: $AWS_ACCESS_KEY_ID"
          echo "secret aws: $AWS_SECRET_ACCESS_KEY"
                 
